version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: hr_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-hr_management}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-hr_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-hr_password}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - hr_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Laravel Backend
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: hr_backend
    restart: unless-stopped
    working_dir: /var/www
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-hr_management}
      DB_USERNAME: ${DB_USERNAME:-hr_user}
      DB_PASSWORD: ${DB_PASSWORD:-hr_password}
      JWT_SECRET: ${JWT_SECRET:-your-jwt-secret-key}
    ports:
      - "8000:80"
    volumes:
      - ./server:/var/www
      - /var/www/vendor
      - ./server/storage:/var/www/storage
      - ./server/bootstrap/cache:/var/www/bootstrap/cache
    depends_on:
      db:
        condition: service_healthy
    networks:
      - hr_network

  # Vue.js Frontend
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development-stage
    container_name: hr_frontend
    restart: unless-stopped
    environment:
      VUE_APP_API_URL: http://localhost:8000/api
      VUE_APP_BASE_URL: http://localhost:8000
    ports:
      - "8080:8080"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - hr_network

  # Redis (optional - for caching/sessions)
  redis:
    image: redis:alpine
    container_name: hr_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - hr_network

volumes:
  mysql_data:
    driver: local

networks:
  hr_network:
    driver: bridge